name: release
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    name: publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: publish oci-distribution to crates.io
        run: cargo publish --token ${{ secrets.CargoToken }}
