name: release
on:
  push:
    tags:
      - "v*"
jobs:
  publish:
    name: publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: publish oci-distribution to crates.io
        run: cargo publish --token ${{ secrets.CargoToken }}
