name: release
on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: publish to crates.io
    runs-on: ubuntu-latest
    needs: build-and-test-nodejs
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: publish oci-distribution to crates.io
        run: cargo publish --token ${{ secrets.CargoToken }}

  # Build and test Node.js bindings FIRST
  # This also ensures version sync before any publishing
  build-and-test-nodejs:
    name: Build & Test Node.js
    uses: ./.github/workflows/nodejs-build-call.yml

  # Publish Node.js packages to npm
  publish-nodejs-bindings:
    name: Publish to npm
    uses: ./.github/workflows/nodejs-publish-call.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
